stages:
  - build
  - deploy

build-frontend:
  stage: build
  image: node
  cache:
    key:
      prefix: "hcmobile"
      files:
        - "/package-lock.json"
    paths:
      - "node_modules/"
  before_script:
    - "yarn install --force"
  script:
    - yarn run build
  artifacts:
    paths:
      - .next

deploy_stage:
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
  stage: deploy
  only:
    - main
  script:
    - sshpass -V
    - export SSHPASS=$CI_USER_PASS
    - sshpass -e scp -r  -o StrictHostKeyChecking=no .next gitlab-ci@146.190.223.178:/home/gitlab-ci/other-sites
