stages:
  - build                                                                                                                                        
  - deploy 

build-frontend:
  stage: build
  image: node
  cache:
    key:
      prefix: 'hcmobile'
      files:
        - '/package-lock.json'
    paths:
      - 'node_modules/'
  before_script:
    - 'npm i --force'
  script:
    - npm run build
  artifacts:
    paths:
      - dist/hcmobile

deploy_stage:
  before_script:                                                                                                                                
    - apt-get update -qq && apt-get install -y -qq sshpass
  stage: deploy
  only:
    - main
  script:
    - sshpass -V                                                                                                                                
    - export SSHPASS=$CI_USER_PASS
    - sshpass -e scp -r  -o StrictHostKeyChecking=no dist/hcmobile gitlab-ci@146.190.223.178:/home/gitlab-ci/other-sites                          
   