import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslations } from 'next-intl';

import AccountSection from '../components/landingpage/AccountSection';
import Hero from '../components/landingpage/Hero';
import About from '../components/landingpage/About';
import AppSteps from '../components/landingpage/AppSteps';
import Services from '../components/landingpage/Services';
import Reviews from '../components/landingpage/Reviews';
import NewsSection from '../components/landingpage/NewsSection';
import Footer from '../components/landingpage/Footer';
import Header from '../components/landingpage/Header';
import { app_config } from '../utils/constants';
import { withLocaleMessages } from '../utils/ssg/withLocaleMessages';

const Home: NextPage = () => {
  const t = useTranslations('Home')
  return (
    <>
      <Head>
        <title>{`${app_config.APP_NAME}`}</title>
        <meta name="description" content="Generated by HCM corporations ltd" />
        <link rel="icon" href={app_config.APP_LOGO} type="image/x-icon" />
      </Head>

      <header>
        <Header/>
    </header>
      <main>
      <Hero/>
        <AccountSection/>
        <About/>
        <AppSteps/>
        <Services/>
        <Reviews/>
        <NewsSection/>
      </main>
      <footer>
        <Footer/>
    </footer>

    </>
  )
}

export default Home;

export async function getStaticProps ({locale} : any){
  return { 
    props : {
      messages : {
        ...require(`../locales/${(locale ?? 'en-us').toLocaleLowerCase()}.json`)
      }
    }
  }
}