import type { NextPage } from 'next'
import Head from 'next/head'

import HomePage from '../components/LandingPage/HomePage'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>HCM Appointment System</title>
        <meta name="description" content="Generated by HCM corporations app" />
        <link rel="icon" href="https://www.mod.gov.rw/index.php?eID=dumpFile&t=f&f=1679&token=c456432515e20118795fbbd0cce379ac2bcd0a14" />
      </Head>

      <main>
        <HomePage/>
      </main>

    </>
  )
}

export default Home
