import type { NextPage } from 'next';
import Head from 'next/head';

import AccountSection from '../components/landingpage/AccountSection';
import Hero from '../components/landingpage/Hero';
import About from '../components/landingpage/About';
import AppSteps from '../components/landingpage/AppSteps';
import Services from '../components/landingpage/Services';
import Reviews from '../components/landingpage/Reviews';
import NewsSection from '../components/landingpage/NewsSection';
import Footer from '../components/landingpage/Footer';
import Header from '../components/landingpage/Header';
import { app_config } from '../utils/constants';
import { useRouter } from 'next/router';
import { useTranslations } from 'next-intl';

export default function Home() {
  const t = useTranslations('Homepage')
  const { locale } = useRouter()
  return (
    <>
      <Head>
        <title>{`${app_config.APP_NAME}`}</title>
        <meta name="description" content="Generated by HCM corporations ltd" />
        <link rel="icon" href={app_config.APP_LOGO} type="image/x-icon" />
      </Head>
      <Header />
      <main>
        <Hero />
        <AccountSection />
        <About />
        <AppSteps />
        <Services />
        <Reviews />
        <NewsSection />
      </main>
      <footer>
        <Footer />
      </footer>

    </>
  )
}

export function getStaticProps({ locale }: any) {
  return {
    props: {
      messages: {
        ...require(`../locales/${locale}.json`),
      },
    },
  }
}
// ...require(`../locales/${(locale ? locale :'en-us'.toLocaleLowerCase()}.json`)